### ISSUE TITLE
Add bibtex info to a __bibtex__ variable in __init__.py

### ISSUE THREAD

**Issue by FaustinCarter** [SebastianBocquet/pygtc#12]
Title says it all. All the other cool-kid packages are doing this.

**Comment by SebastianBocquet** [comment]
Not sure how much I like this as it seems unnecessarily cumbersome. How about adding
`__url__ = 'https://pygtc.readthedocs.io/'`
instead where people can get _all_ the information.

**Comment by FaustinCarter** [comment]
Sounds good. Closing.
