### ISSUE TITLE
Update for compatibility with MPL 3.0

### ISSUE THREAD

**Issue by FaustinCarter** [SebastianBocquet/pygtc#13]
With the new release of Matplotlib 3, we need to verify everything still works!

**Comment by SebastianBocquet** [comment]
This will be harder than expected because
`The ImageComparisonTest class was deprecated in Matplotlib 3.0 and will be removed in 3.2.`

**Comment by SebastianBocquet** [comment]
On a related note, how about having pip install the tests as well so that people can check their pip-installed pygtc?

**Comment by FaustinCarter** [comment]
Doesn't look like any of our open matplotlib issues have been addressed... shame. Was hoping we could clean up some of that code.

https://github.com/matplotlib/matplotlib/issues/created_by/FaustinCarter
