### ISSUE TITLE
ChainLabels Flagging Errant Error

### ISSUE THREAD

**Issue by exowanderer** [SebastianBocquet/pygtc#14]
When using ChainLabels with very obvious labels vs chain sizes, `pygtc` returns the `AssertionError`

`AssertionError: chainLabels mismatch with number of chains`

The traceback is very short, which says

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-50-cef684fceb1f> in <module>
     10 #                   customTickFont={'family':'Arial', 'size':20},
     11                   chainLabels = np.array(list(df_in.columns)),
---> 12                   figureSize=40)

~/anaconda3/lib/python3.6/site-packages/pygtc/pygtc.py in plotGTC(chains, **kwargs)

AssertionError: chainLabels mismatch with number of chains
```

Here is a simple example that triggers the issue:

```python
import numpy as np
from pygtc import plotGTC

chains = np.random.normal(0,1, (100000, 19))

pygtc_out = plotGTC(chains, chainLabels = np.arange(chains.shape[1]))
```

**Comment by SebastianBocquet** [comment]
So you are trying to plot a single chain that has 100000 samples in 19 dimensions. Therefore, pygtc expects a single `chainLabel`.

If you want to plot 5 chains with 100000 samples in 3 dimensions, you would do

```import numpy as np
from pygtc import plotGTC

chains = np.random.normal(0, 1, (5, 100000, 3))

pygtc_out = plotGTC(chains,
                    chainLabels = ['0', '1', '2', '3', '4'],
                   )
```

Hope this helps!

**Comment by FaustinCarter** [comment]
@exowanderer: It occurs to me that you are perhaps meaning to use the `'paramNames'` keyword argument, which labels the individual dimensions of a single chain. The `'chainLabels'` keyword argument, as @SebastianBocquet pointed out, is meant for when you are over plotting multiple chains on the same set of axes.

**Comment by exowanderer** [comment]
You are correct. I need `paramNames`.  When scanning through the keyword arguments, chainlabels was the first and "most obvious" connection to "label for each chain", meaning the parameters of each chain. In all of MCMC routines, the fitted parameters are all referred to as "chains". 

But I understand why you separated those for this use. Your priority is multiple model fits with overlapping posteriors.  

Thank you.
