### ISSUE TITLE
TypeError when setting xlabel

### ISSUE THREAD

**Issue by joergdietrich** [SebastianBocquet/pygtc#4]
c&p the minimal example from http://pygtc.readthedocs.io/en/latest/demo.html I get

```

In [13]: GTC = pygtc.plotGTC(chains=[samples1,samples2])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/joerg/PAPER/sptoir/2017/Megacam_19/scripts/plot_GTC_Yx.py in <module>()
----> 1 GTC = pygtc.plotGTC(chains=[samples1,samples2])

/home/joerg/applications/anaconda3/lib/python3.5/site-packages/pygtc/pygtc.py in plotGTC(chains, **kwargs)
    645                         #shift the x labels when it gets called during render
    646                         xLabel.set_x = types.MethodType(lambda self, x: mpl.text.Text.set_x(self, x+self.custom_shift),
--> 647                                     xLabel, mpl.text.Text)
    648 
    649                         #Update the font if needed

TypeError: method expected 2 arguments, got 3
```

**Comment by FaustinCarter** [comment]
I suspect that the problem might have to do with Python 3.5. We haven't explicitly supported Python 3 yet, but I suppose we should start doing that. Can you switch to python 2 (super easy since you are running anaconda) and try again?

I've opened a new ticket regarding the Python 3 support.

**Comment by joergdietrich** [comment]
It's working in python 2.7. `six.create_bound_method` may help you here.

**Comment by FaustinCarter** [comment]
This has been fixed. Python 3 omits the final argument of MethodType (Class) and instead just figures it out from the instance argument. Now pygtc checks for python version and makes the appropriate call.
